---
# INSTALL
- name: Install Portainer on all nodes
  tags: gui_portainer_ce_install
  vars:
    container: "{{ gui_portainer[0] }}"
  docker_container:
    name: "{{ container.name }}"
    hostname: "{{ container.hostname }}"
    image: "{{ container.image }}"
    command: "{{ container.command | default(omit) }}"
    state: started
    restart_policy: "{{ container.restart_policy | default('always') }}"
    rm: "{{ container.rm | default(omit) }}"
    memory: "{{ container.memory | default(omit) }}"
    ports: "{{ container.ports | default(omit) }}"
    env: "{{ container.env | default(omit) }}"
    env_file: "{{ container.env_file | default(omit) }}"
    volumes: "{{ container.volumes | default(omit) }}"
    healthcheck: "{{ container.healthcheck | default(omit) }}"

# START
- name: Start Portainer on all nodes
  tags: gui_portainer_ce_start
  vars:
    container: "{{ gui_portainer[0] }}"
  docker_container:
    name: "{{ container.name }}"
    state: started

# RESTART
- name: Restart Portainer on all nodes
  tags: gui_portainer_ce_restart
  vars:
    container: "{{ gui_portainer[0] }}"
  docker_container:
    name: "{{ container.name }}"
    state: started
    restart: true

# STOP
- name: Stop Portainer on all nodes
  tags: gui_portainer_ce_stop
  vars:
    container: "{{ gui_portainer[0] }}"
  docker_container:
    name: "{{ container.name }}"
    state: stopped

# UNINSTALL
- name: Uninstall Portainer on all nodes
  tags: gui_portainer_ce_uninstall
  vars:
    container: "{{ gui_portainer[0] }}"
  docker_container:
    name: "{{ container.name }}"
    state: absent
    force_kill: true

- name: Remove portainer_data volume on all nodes
  tags: gui_portainer_ce_uninstall
  docker_volume:
    name: "portainer_datas"
    state: absent
