KPOW_CE_LICENSE_ID: 51484dbf-2702-443e-8cdd-f330c5ecec0b
KPOW_CE_LICENSE_CODE: KPOW_COMMUNITY
KPOW_CE_LICENSEE: Arkady Rosenberg
KPOW_CE_LICENSE_EXPIRY: 2026-02-09
KPOW_CE_LICENSE_SIGNATURE: 69AE022D803C453D42C643B14432C7143A489F2C16B8B284FF295FC47A3053F2F93A31CAFA8D799051339557F9DFCB5E854056F3DF5E999C0A7AC63CF64DE7857AE4E50E1DF36B516BF547CC18CCBC79BCC0106C77789E421B8706E82F70771771F57048FEA801B05072AB76D8A9E3EFD51F70BAED5D0C7027283F6DBAEB38B1

KPOW_CE_ENVIRONMENT_NAME: Kafka 3.9.0 Cluster
KPOW_CE_SCHEMA_REGISTRY_NAME: Schema Cluster
KPOW_CE_CONNECT_NAME: Connect Cluster
KPOW_CE_KSQLDB_NAME: KSQL Cluster
