KPOW_CE_LICENSE_ID: 2539bf86-2f70-4344-bcfd-ed12a20693b2
KPOW_CE_LICENSE_CODE: COMMUNITY
KPOW_CE_LICENSEE: Arkady Rozenberg
KPOW_CE_LICENSE_EXPIRY: 2027-02-08
KPOW_CE_LICENSE_SIGNATURE: A25F67926ADD2DA40309023F27D180338F82BEEA4BF379C43AA129C1393C207D0AC9F7002CF1432BB7328E02B8DD8C3798FD538441EC4214014809962C915EE9E07C1729184BCFA307ACB3AFCBB63BD1DC98DFC1419BE60709F012A42905850399E157844D5CBAFE787AF42DF950A8C827D94C12A01CC065E218FF8E829691AE

KPOW_CE_ENVIRONMENT_NAME: Apache Kafka 4.1.0
KPOW_CE_CONNECT_NAME: Apache Connect 4.1.0
KPOW_CE_SCHEMA_REGISTRY_NAME: Confluent Schema 8.1.0
KPOW_CE_KSQLDB_NAME: Confluent KSQL 8.1.0
