---
- name: Validate containers status
  tags:
    - cluster_restore
  # all of them, not only controllers and brokers, lets be on the safe side
  when: "'cluster' in group_names"
  include_tasks: ../../docker/tasks/containers_validation.yml

- name: Verify archive exists
  tags:
    - cluster_restore
  when: inventory_hostname == "node-00"
  ansible.builtin.stat:
    path: "{{ restore_archive }}"
  register: archive_stat

- name: Fail if snapshot not found
  tags:
    - cluster_restore
  when: inventory_hostname == "node-00" and not archive_stat.stat.exists
  ansible.builtin.fail:
    msg: "The specified restore archive {{ restore_archive }} does not exist!"

# -------------------------------------------------------------------
# Prepare backup directory in cold storage
# -------------------------------------------------------------------
- name: Ensure zip-of-zips folder exists in central temp storage
  tags: cluster_restore
  when: inventory_hostname == "node-00"
  ansible.builtin.file:
    path: "{{ storage_temp_path }}/zip-of-zips/"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_data }}"
    state: directory

# -------------------------------------------------------------------
# Extract snapshot on node-00 into a temp directory
# -------------------------------------------------------------------
- name: Extract snapshot tar.xz into temp/zip-of-zips
  tags:
    - cluster_restore
  when: inventory_hostname == "node-00"
  ansible.builtin.shell:
    cmd: >
      xz -dc "{{ restore_archive }}" |
      tar -xf - -C "{{ storage_temp_path }}/zip-of-zips/"

# -------------------------------------------------------------------
# Push per-node archives to each node
# -------------------------------------------------------------------
- name: Push archives back to nodes
  tags:
    - cluster_restore
  delegate_to: node-00
  synchronize:
    src: "{{ storage_temp_path }}/zip-of-zips/{{ inventory_hostname }}/"
    dest: "{{ node_temp_path }}/restore/"
    mode: push
    rsync_opts:
      - "--delete"
      - "--checksum"

- name: Remove Cluster Folders on nodes
  tags:
    - cluster_restore
  ansible.builtin.file:
    path: "{{ node_data_store }}"
    state: absent

- name: Create Cluster Folders on nodes
  tags:
    - cluster_restore
  ansible.builtin.file:
    path: "{{ node_data_store }}"
    owner: "{{ owner_user_data }}"
    group: "{{ owner_group_data }}"
    mode: "{{ chmod_data }}"
    state: directory

# -------------------------------------------------------------------
# Restore data on each node
# Example: restore /data/cluster/<folder>
# -------------------------------------------------------------------
- name: Restore cluster data from archives
  tags:
    - cluster_restore
  ansible.builtin.shell:
    cmd: >
      for archive in {{ node_temp_path }}/restore/*.tar.xz; do
        xz -dc "$archive" | tar -xpf - -C "{{ node_storage_base }}";
      done
