---
- include_tasks: containers_install.yml
  tags: containers_install

- include_tasks: containers_start.yml
  tags: containers_start

- include_tasks: containers_stop.yml
  tags: containers_stop

- include_tasks: containers_restart.yml
  tags: containers_restart

- include_tasks: containers_uninstall.yml
  tags: containers_uninstall

